name: Unit Test and build

on:
  push:
    branches: 
      - main
      - release*

env:
  server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  username: ${{ secrets.ACR_USERNAME }}
  password: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Build the docker image
        run: docker build . -t ${{ env.server }}/frontend:${{ github.ref_name }}-${{ github.run_number }}
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.server }}
          username: ${{ env.username }}
          password: ${{ env.password }}
      - name: Push the docker image
        run: docker push ${{ env.server }}/frontend:${{ github.ref_name }}-${{ github.run_number }}
