name: Pre-check

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3 
      - name: Runs test
        run: npm test
    
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3 
      - name: Build
        run: npm run build
    